Homework2
ValeryKhandryonkov/ValeryKhandryonkov_LevelUp pull request #15
Opened 2022-11-25 20:15 UTC by ValeryKhandryonkov

2022-11-28 07:02 UTC, khda91 requested changes
Не плохая работа, но необходимо исправить комментарии

2022-11-28 07:02 UTC, khda91 commented on .gitignore
> +.editorconfig
Его можно не игнорировать, так как он должен быть один для всей команды, чтобы код форматировался в едином формате

2022-11-28 07:02 UTC, khda91 commented on src/main/java/ru/levelp/at/homework2/LuckyTicket.java
> +        if (ticketNumber != null && !ticketNumber.isEmpty()) {
Я бы предложил тут немного переделать. Очень много ветвлений и не все они нужны. 
Плюс я не вижу выброса ошибки, если что-то пошло не так. 

Для первого `if` можно было бы сделать обратную проверку из серии: 
```java
if (ticketNumber == null) {
    throw new IllegalArgumentException("Some message here...");
}
```

2022-11-28 07:02 UTC, khda91 commented on src/main/java/ru/levelp/at/homework2/LuckyTicket.java
> +            if (ticketNumber.length() == 6) {
Эти 2 проверки можно объединить в одну используя метод `matches` класса `String`, который принимает в себя регулярное выражение, которому строка должна соответвовать. 

```java
if (!ticketNumber.matches("...")) {
    throw new IllegalArgumentException("Some message here...");
}
```

2022-11-28 07:02 UTC, khda91 commented on src/main/java/ru/levelp/at/homework2/LuckyTicket.java
> +                    System.out.print("The ticket is lucky! Congratulations! \n");
В целом тут весь этот вывод не нужен. можно просто `return firstHalfSum == secondHalfSum;`

2022-11-28 07:02 UTC, khda91 commented on src/test/java/ru/levelp/at/homework2/LuckyTicketNegativeTest.java
> +        assertThat(actual).isEqualTo(expected);
Для всей это пачки тестов, я бы ожидал, что метод `isLuckyTicket` будет выбрасывать сообщение об ошибке и исключение, что формат данных не правильный, а не возвращать `false`

2022-11-28 07:02 UTC, khda91 commented on src/test/java/ru/levelp/at/homework2/LuckyTicketPositiveTest.java
> +    }
А по чему тесты помечены как **Positive**? Больше похоже на негативные тесты. И если это негативные тесты, то в этом случае мы тоже ожидаем некого исключения

2022-11-28 21:18 UTC, ValeryKhandryonkov commented on .gitignore
> +.editorconfig
Удалил .editorconfig из .gitignore

2022-11-28 21:19 UTC, ValeryKhandryonkov commented on src/main/java/ru/levelp/at/homework2/LuckyTicket.java
> +        if (ticketNumber != null && !ticketNumber.isEmpty()) {
Убрал лишние ветвления, добавил проверку на получение значения null вместо номера билета.

2022-11-28 21:21 UTC, ValeryKhandryonkov commented on src/main/java/ru/levelp/at/homework2/LuckyTicket.java
> +            if (ticketNumber.length() == 6) {
Заменил эти две проверки регулярным выражением, теперь метод выбрасывает исключение IllegalArgumentException, если в номере билета есть символы отличные от цифр и длина билета не равна шести символам.

2022-11-28 21:25 UTC, ValeryKhandryonkov commented on src/main/java/ru/levelp/at/homework2/LuckyTicket.java
> +                    System.out.print("The ticket is lucky! Congratulations! \n");
Изначально этот вывод помогал в отладке, потом решил его оставить. Сейчас убрал лишние строки вывода в консоль. Сократил используемый if/else до рекомендуемого return firstHalfSum == secondHalfSum.

2022-11-28 21:26 UTC, ValeryKhandryonkov commented on src/test/java/ru/levelp/at/homework2/LuckyTicketNegativeTest.java
> +        assertThat(actual).isEqualTo(expected);
Поправил тест. Теперь проверяет, что получаем ожидаемое исключение.

2022-11-28 21:31 UTC, ValeryKhandryonkov commented on src/test/java/ru/levelp/at/homework2/LuckyTicketPositiveTest.java
> +    }
В задании явно не указано, что номер билета не может быть меньше или больше шести знаков, поэтому считал, что такие номера билетов тоже валидны, но не являются счастливыми, поэтому тест и считал позитивным, по аналогии с тестом где билет имеет шестизначный номер, но суммы половинок не равны.
Поправил. Теперь это негативные тесты, в которых метод выбрасывает исключение в соответствии с добавленной проверкой по регулярному выражению.

2022-12-01 14:37 UTC, khda91 approved these changes
Homework accepted

2022-12-01 14:37 UTC, merged