Homework3
ValeryKhandryonkov/ValeryKhandryonkov_LevelUp pull request #16
Opened 2022-12-02 20:54 UTC by ValeryKhandryonkov

2022-12-06 13:03 UTC, khda91 requested changes
Пара комментариев, а так очень хорошая работа

2022-12-06 13:03 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/FirstExerciseTest.java
> +    }
В целом этот кусочек можно вынести в `BaseTest`

2022-12-06 13:03 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/SecondExerciseTest.java
> +
Выглядит как кусок, который был в пердыдущем классе

2022-12-07 20:34 UTC, ValeryKhandryonkov commented on src/test/java/ru/levelp/at/homework3/FirstExerciseTest.java
> +    }
Создал базовый класс и вынес в него @BeforEach и @AfterEach

2022-12-07 20:36 UTC, ValeryKhandryonkov commented on src/test/java/ru/levelp/at/homework3/SecondExerciseTest.java
> +
Вынес в базовый класс все переменные с неуникальными значениями (все кроме темы и текста письма).

2022-12-10 09:40 UTC, khda91 approved these changes
работа принята

2022-12-11 17:22 UTC, merged