Homework4
ValeryKhandryonkov/ValeryKhandryonkov_LevelUp pull request #17
Opened 2022-12-08 21:28 UTC by ValeryKhandryonkov

2022-12-10 09:50 UTC, khda91 requested changes
2 небольших замечания

2022-12-10 09:50 UTC, khda91 commented on src/main/java/ru/levelp/at/homework4/MainPage.java
> +    private final WebDriverWait wait;
Лучше конечно бы вынести эту переменную в базовй класс, чтобы можно было создать 1 ожидение для всех страниц

2022-12-10 09:50 UTC, khda91 commented on src/test/java/ru/levelp/at/homework4/BaseSeleniumTest.java
> +        wait = new WebDriverWait(driver, Duration.ofMillis(10000));
При использовании PageObjects явное ожидание уже не нужно указывать в тестах

2022-12-11 17:24 UTC, ValeryKhandryonkov commented on src/main/java/ru/levelp/at/homework4/MainPage.java
> +    private final WebDriverWait wait;
Создал класс BasePage и перенёс в него WebDriverWait из MainPage и LoginRegistrationPage.

2022-12-11 17:25 UTC, ValeryKhandryonkov commented on src/test/java/ru/levelp/at/homework4/BaseSeleniumTest.java
> +        wait = new WebDriverWait(driver, Duration.ofMillis(10000));
Удалил WebDriverWait из BaseSeleniumTest.

2022-12-20 19:29 UTC, khda91 approved these changes
Работа принята

2022-12-20 21:39 UTC, merged